#cloud-config
users:
  - name: lucamaggio
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCJ175LOzqNnLcBjNtfYppwNjna+S5EK86VtX+vXfkdTCD6z8BznAwKyy1K7OQX3cfHHtge6A2/Tg+fWqVXE14XChxhBoHYPe6t0tCPgjkm0q+NHgRfpFvMrmJ/gphBp91kzN/bTNCcaVmqEHvt82yeii/X15LgoFOfTSEEELrFjEIxdYzTyxHG0/xtos6WHlLNZe/+hXLj3Flad3sCxa7sKbqupBkyoQO3gVfdYnf3e0Ic5xBSO2UV1SmGbGpgd3uPk+NvIsYtJYyBxLQxqnRj7QHH3KHiLb1D3aQx1n/ieCbhU726o8/iveDZyOVvGFFNxhwI9YF4lQFP+AuP7U7HeUUqbhjNJurpSAaWRO7VDSY+19VJxAsQfd+vz/niYJlWGzHazI/LBdNebPQMAcIhOHMnV68FHtJJtkjm1jHcZy6VI28GSy2ZbEQpMQFMtjrmPBo8bkp2UR+1al+7cVL1Z22e/mZeueYnP3sGQfMNbPdc85tyzP9gsWkjdWRonSc= lucamaggio@lucamaggio-Vostro-3520
packages:
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - curl
  - software-properties-common
  - containerd
runcmd:
  - apt-get update
  - systemctl enable containerd.service
  - containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
  - swapoff -a
  - sed -i '/swap/ s/^/#/' /etc/fstab
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' > /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet=1.28.15-1.1 kubeadm=1.28.15-1.1 kubectl=1.28.15-1.1
  - apt-mark hold kubelet kubeadm kubectl

